### ISSUE TITLE
MQTT required?

### ISSUE THREAD

**Issue by TheFes** [brandond/esphome-tuya_pir#23]
Is MQTT required to have the door sensor working in Home Assistant?
I would expect that the binary sensor is exposed to HA, and the status of the binary sensor could be used to trigger automations.

In case it is not required, would the code then also work without the custom component?
So something like this?
```yaml
esphome:
  name: door
  platform: ESP8266
  board: esp01_1m
  arduino_version: 2.5.1
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true

uart:
  - tx_pin: 1
    rx_pin: 3
    baud_rate: 9600
    id: uart0

ota:

logger:
  level: INFO
  hardware_uart: UART1

sensor:
  - platform: wifi_signal
    name: "Door WiFi Signal"
    update_interval: 60s
  - platform: adc
    name: "Door Battery"
    update_interval: 60s
    pin: VCC

binary_sensor:
  - platform: template
    id: door
    name: "Door Closure"
    filters: []
    device_class: door
    lambda: "return {};"
```
